server:
   port: ${PORT:8863}
message: Configuracion de Cajero en el servidor levantado!
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/dbcrudcloud
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQLDialect
  cloud:
    config:
      uri: http://localhost:8080
   eureka:
     client:
       register-with-eureka: true
#      fetch-registry: false
       serviceurl:
         defaultZone: http://localhost:8850/eureka/
