server:
   port: ${PORT:8867}
eureka:
  client:
  # fetch-registry: false 
    register-with-eureka: true
    serviceurl:
      defaultZone: http://localhost:8850/eureka/
message: Configuracion de Categoria en el servidor levantado!
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/dbcrudcloud
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQLDialect
  cloud:
    config:
      uri: http://localhost:8080

